name = input('Please, enter your name: ')
age = int(input('Please, enter your age: '))
print(f'your name is {name} and you are {age:^25}')
# print(f'your name is {name} and you are {age:<25}')
# print(f'your name is {name} and you are {age:>25}')
